name: Automated Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: cs backend
      - run: npm install
      - run: npm test
